"use client";

import { CreditCard } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

import {
  EmptyState,
  PageError,
  PageHeader,
  PageLoader,
} from "@/components/dashboard/page-shell";
import { Badge, statusBadgeVariant } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { parseApiError } from "@/lib/api-utils";
import { getMyRents } from "@/lib/rents";
import type { Rent } from "@/types/rent";

export default function MyRentsPage() {
  const [rents, setRents] = useState<Rent[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    try {
      setError(null);
      const data = await getMyRents();
      setRents(data);
    } catch (err) {
      setError(parseApiError(err, "Unable to load your rent history."));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  if (loading) return <PageLoader label="Loading your rents..." />;
  if (error) return <PageError message={error} />;

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Payments"
        title="My Rents"
        description="View your monthly rent records and payment status."
      />

      {rents.length === 0 ? (
        <EmptyState
          title="No rent records"
          description="Your rent history will appear here once generated by management."
        />
      ) : (
        <div className="grid gap-4">
          {rents.map((rent) => (
            <Card key={rent.id}>
              <CardHeader className="flex-row items-start justify-between gap-4">
                <div>
                  <CardTitle className="flex items-center gap-2">
                    <CreditCard className="size-4 text-primary" />
                    {rent.rent_month}
                  </CardTitle>
                  <CardDescription>
                    Due on {rent.due_date}
                    {rent.paid_date ? ` · Paid on ${rent.paid_date}` : ""}
                  </CardDescription>
                </div>
                <Badge variant={statusBadgeVariant(rent.status)}>
                  {rent.status}
                </Badge>
              </CardHeader>
              <CardContent className="grid gap-2 text-sm sm:grid-cols-3">
                <p>
                  <span className="text-muted-foreground">Amount: </span>₹
                  {rent.amount}
                </p>
                <p>
                  <span className="text-muted-foreground">Paid: </span>₹
                  {rent.amount_paid}
                </p>
                <p>
                  <span className="text-muted-foreground">Late fee: </span>₹
                  {rent.late_fee}
                </p>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
